// Package docsgen plans documentation derived from a project inspection.
package docsgen

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/fvmoraes/ginger/internal/manifest"
	"github.com/fvmoraes/ginger/internal/plan"
	"github.com/fvmoraes/ginger/internal/project"
)

// BuildPlan generates managed Markdown files without replacing custom docs.
func BuildPlan(prj *project.Project, force bool) (*plan.Plan, error) {
	report, err := project.Inspect(prj)
	if err != nil {
		return nil, err
	}
	docsDir, err := prj.ResolvePath("docs")
	if err != nil {
		return nil, err
	}
	ownership, err := manifest.Load(prj.Root)
	if err != nil {
		return nil, err
	}
	files := map[string]string{
		"architecture.md":  architecture(report),
		"routes.md":        routes(report),
		"configuration.md": configuration(report),
		"development.md":   development(report),
		"testing.md":       testingDoc(report),
		"deployment.md":    deployment(report),
	}
	p := plan.New(prj.Root)
	p.CreateMissingDirs = prj.YAML.Rules.CreateMissingDirs
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	var entries []manifest.Entry
	for _, name := range names {
		path := filepath.Join(docsDir, name)
		rel, _ := filepath.Rel(prj.Root, path)
		before := len(p.Changes)
		p.AddCreate(path, []byte(files[name]), force || prj.ShouldOverwrite() || ownership.ManagesFullFile(rel))
		if len(p.Changes) > before {
			change := p.Changes[len(p.Changes)-1]
			if change.Type == plan.ChangeCreate || change.Type == plan.ChangeModify {
				entries = append(entries, manifest.Entry{Path: filepath.ToSlash(rel), FullFile: true})
			}
		}
	}
	if len(entries) > 0 {
		if err := manifest.PlanUpdate(p, entries...); err != nil {
			return nil, err
		}
	}
	return p, nil
}

func architecture(report *project.Inspection) string {
	var out strings.Builder
	fmt.Fprintf(&out, "# Architecture\n\nGenerated by Ginger from `%s`.\n\n| Area | Path | Present |\n|---|---|---|\n", report.Module)
	keys := make([]string, 0, len(report.Structure))
	for key := range report.Structure {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		status := report.Structure[key]
		fmt.Fprintf(&out, "| %s | `%s` | %t |\n", key, status.Path, status.Exists)
	}
	return out.String()
}

func routes(report *project.Inspection) string {
	var out strings.Builder
	out.WriteString("# Routes\n\n| Method | Path | Source |\n|---|---|---|\n")
	for _, route := range report.Routes {
		fmt.Fprintf(&out, "| %s | `%s` | `%s:%d` |\n", route.Method, route.Path, route.File, route.Line)
	}
	if len(report.Routes) == 0 {
		out.WriteString("\nNo routes detected. Add `// ginger:route METHOD /path` annotations.\n")
	}
	return out.String()
}

func configuration(report *project.Inspection) string {
	status := report.Structure["config"]
	return fmt.Sprintf("# Configuration\n\nConfigured location: `%s` (present: %t).\n\nTODO: document environment variables and defaults.\n", status.Path, status.Exists)
}

func development(report *project.Inspection) string {
	return fmt.Sprintf("# Development\n\nModule: `%s`  \nGo: `%s`\n\n```bash\ngo test ./...\ngo vet ./...\n```\n", report.Module, report.GoVersion)
}

func testingDoc(report *project.Inspection) string {
	return fmt.Sprintf("# Testing\n\nDetected test files: %d.\n\n```bash\nginger generate tests --scan --plan\ngo test ./...\n```\n", report.TestFiles)
}

func deployment(report *project.Inspection) string {
	features := "none detected"
	if len(report.Features) > 0 {
		features = strings.Join(report.Features, ", ")
	}
	return fmt.Sprintf("# Deployment\n\nDetected deployment/runtime features: %s.\n\nTODO: document environment-specific rollout and rollback steps.\n", features)
}
