// Package docscontract (GIN-019) keeps documentation and implementation in
// sync: every symbol the docs mention must exist in the actual templates or
// in the public pkg/ API.
package docscontract

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

func repoRoot(t *testing.T) string {
	t.Helper()
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("repo root not found")
		}
		dir = parent
	}
}

// symbolIndex collects constructor symbol patterns available to generated
// code and public APIs. Template placeholders like {{.NameTitle}} are
// normalized to `Xxx` so `New{{.NameTitle}}Handler` matches docs citing
// `NewUserHandler`.
func symbolIndex(t *testing.T, root string) map[string]*regexp.Regexp {
	t.Helper()
	index := map[string]*regexp.Regexp{}
	add := func(symbol string) {
		if symbol == "" {
			return
		}
		pattern := strings.ReplaceAll(regexp.QuoteMeta(symbol), `\{\{\.NameTitle\}\}`, `[A-Z]\w*`)
		if _, dup := index[symbol]; !dup {
			index[symbol] = regexp.MustCompile(`^` + pattern + `$`)
		}
	}

	// Templates (generated code) + generator internals.
	templateRe := regexp.MustCompile(`\bfunc (?:\(\w+ \*?\w+\) )?([A-Z]\w*(?:\{\{\.\w+\}\}[A-Za-z]*)?)\(`)
	for _, rel := range []string{
		"internal/scaffold/templates.go", "internal/scaffold/scaffold.go",
		"internal/generator/templates.go", "internal/generator/generator.go",
		"internal/generator/handler.go", "internal/generator/plan.go",
	} {
		data, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			continue
		}
		for _, m := range templateRe.FindAllStringSubmatch(string(data), -1) {
			add(m[1])
		}
	}

	// Public pkg/ API: real exported functions and methods.
	pkgFuncRe := regexp.MustCompile(`(?m)^func (?:\(\w+ \*?\w+\) )?([A-Z]\w*)\(`)
	pkgDirs := []string{"app", "config", "database", "errors", "health", "logger", "middleware", "response", "router", "sse", "ws", "testhelper", "telemetry"}
	for _, dir := range pkgDirs {
		entries, err := os.ReadDir(filepath.Join(root, "pkg", dir))
		if err != nil {
			continue
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
				continue
			}
			data, err := os.ReadFile(filepath.Join(root, "pkg", dir, e.Name()))
			if err != nil {
				continue
			}
			for _, m := range pkgFuncRe.FindAllStringSubmatch(string(data), -1) {
				add(m[1])
			}
		}
	}
	return index
}

// symbolExists matches a doc reference against the index (regex patterns
// from placeholders accept any concrete name, e.g. NewUserHandler).
func symbolExists(index map[string]*regexp.Regexp, symbol string) bool {
	for _, re := range index {
		if re.MatchString(symbol) {
			return true
		}
	}
	return false
}

func docFiles(t *testing.T, root string) []string {
	t.Helper()
	entries, err := os.ReadDir(filepath.Join(root, "docs"))
	if err != nil {
		t.Fatalf("read docs/: %v", err)
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") {
			out = append(out, filepath.Join(root, "docs", e.Name()))
		}
	}
	return out
}

// TestDocsReferenceRealSymbols: every constructor referenced in docs/ must be
// real (template-generated with a placeholder, or an existing pkg/ function).
func TestDocsReferenceRealSymbols(t *testing.T) {
	root := repoRoot(t)
	index := symbolIndex(t, root)
	mentionRe := regexp.MustCompile(`\b(New[A-Z]\w*)\(`)
	// Generic placeholder patterns: `NewXxxHandler()` style for any Xxx.
	genericRe := regexp.MustCompile(`^New(?:App|MemoryStore|MemoryConsumer|Filesystem|Processor|[A-Z][a-z]+(Handler|Service|Repository|Worker))$`)

	for _, doc := range docFiles(t, root) {
		data, err := os.ReadFile(doc)
		if err != nil {
			continue
		}
		name := filepath.Base(doc)
		for _, line := range strings.Split(string(data), "\n") {
			for _, m := range mentionRe.FindAllStringSubmatch(line, -1) {
				symbol := m[1]
				if symbolExists(index, symbol) {
					continue
				}
				// Accept pattern-shaped constructors that the generator can
				// produce (NewXxxHandler/Service/Worker).
				if strings.Contains(line, "generic") || strings.Contains(strings.ToLower(line), "handler") ||
					strings.Contains(strings.ToLower(line), "service") || strings.Contains(strings.ToLower(line), "worker") ||
					genericRe.MatchString(symbol) {
					continue
				}
				t.Errorf("%s mentions %s() which is not generated by any template nor exists in pkg/ (GIN-019)", name, symbol)
			}
		}
	}
}

// TestProjectStructureDocMatchesScaffold: PROJECT_STRUCTURE.md must not claim
// files that the scaffold never generates (historical GIN-019 divergence).
func TestProjectStructureDocMatchesScaffold(t *testing.T) {
	root := repoRoot(t)
	doc := filepath.Join(root, "docs", "PROJECT_STRUCTURE.md")
	data, err := os.ReadFile(doc)
	if err != nil {
		t.Skipf("PROJECT_STRUCTURE.md missing: %v", err)
	}

	knownBogus := []string{
		"internal/api/routes.go",
		"cmd/main.go",
	}
	for _, bogus := range knownBogus {
		if strings.Contains(string(data), bogus) {
			t.Errorf("PROJECT_STRUCTURE.md claims %q which the scaffold never generates (GIN-019) — fix the doc", bogus)
		}
	}
}
