package scaffold

const generatedGoFileHeader = `// PT-BR: Arquivo gerado pelo Ginger. Ajuste conforme a necessidade do seu projeto.
// EN: File generated by Ginger. Adjust it as needed for your project.

`

const goModTmpl = `module {{.Module}}

go {{.GoVersion}}
{{if .UsesGinger}}

require github.com/fvmoraes/ginger v{{.GingerVersion}}
{{end}}
`

const mainTmpl = generatedGoFileHeader + `package main

import (
	"log"

	"{{.Module}}/internal/api"
	"{{.Module}}/internal/api/handlers"
	"{{.Module}}/internal/config"
	gingerapp "github.com/fvmoraes/ginger/pkg/app"
)

func main() {
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config: %v", err)
	}

	app := gingerapp.New(cfg)
	handlers.RegisterHealthChecks(app.Health)

	// PT-BR: Registra as rotas da aplicação.
	// EN: Registers the application routes.
	api.Register(app.Router)

	if err := app.Run(); err != nil {
		log.Fatalf("app: %v", err)
	}
}
`

const cliMainTmpl = generatedGoFileHeader + `package main

import (
	"context"
	"fmt"
	"os/signal"
	"syscall"
	"time"
)

func main() {
	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	fmt.Println("{{.Name}} started")
	fmt.Println("Press Ctrl+C to stop gracefully.")
	<-ctx.Done()
	fmt.Printf("{{.Name}} shutting down at %s\n", time.Now().Format(time.RFC3339))
}
`

const workerMainTmpl = generatedGoFileHeader + `package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os/signal"
	"syscall"

	"{{.Module}}/internal/adapters"
	"{{.Module}}/internal/config"
	"{{.Module}}/internal/worker"
)

func main() {
	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config: %v", err)
	}

	go startHealthServer(cfg.HTTP.Host, cfg.HTTP.Port)

	consumer := adapters.NewMemoryConsumer()
	w := worker.New(consumer, &worker.DefaultHandler{})
	log.Println("worker starting...")
	if err := w.Run(ctx); err != nil {
		log.Fatalf("worker: %v", err)
	}
	log.Println("worker stopped")
}

func startHealthServer(host string, port int) {
	mux := http.NewServeMux()
	mux.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(` + "`" + `{"healthy":true}` + "`" + `))
	})

	addr := fmt.Sprintf("%s:%d", host, port)
	log.Printf("worker health endpoint listening on %s", addr)
	if err := http.ListenAndServe(addr, mux); err != nil && err != http.ErrServerClosed {
		log.Printf("worker health server: %v", err)
	}
}
`

const workerTmpl = generatedGoFileHeader + `package worker

import (
	"context"
	"errors"
	"time"

	"{{.Module}}/internal/ports"
)

// PT-BR: Worker representa o processador de jobs em segundo plano.
// EN: Worker is the background job processor.
type Worker struct {
	consumer   ports.MessageConsumer
	handler    Handler
	retryDelay time.Duration
}

func New(consumer ports.MessageConsumer, handler Handler) *Worker {
	return &Worker{
		consumer:   consumer,
		handler:    handler,
		retryDelay: time.Second,
	}
}

// PT-BR: Run inicia o loop do worker e bloqueia até o ctx ser cancelado.
// EN: Run starts the worker loop and blocks until ctx is cancelled.
func (w *Worker) Run(ctx context.Context) error {
	if w.consumer == nil {
		return errors.New("worker: consumer is nil")
	}
	if w.handler == nil {
		return errors.New("worker: handler is nil")
	}

	msgs, err := w.consumer.Consume(ctx)
	if err != nil {
		return err
	}

	for {
		select {
		case <-ctx.Done():
			return nil
		case msg, ok := <-msgs:
			if !ok {
				return nil
			}
			if err := w.handler.Handle(ctx, msg); err != nil {
				_ = w.consumer.Nack(ctx, msg)
				select {
				case <-ctx.Done():
					return nil
				case <-time.After(w.retryDelay):
				}
				continue
			}
			_ = w.consumer.Ack(ctx, msg)
		}
	}
}
`

const internalConfigTmpl = generatedGoFileHeader + `package config

import (
	gingercfg "github.com/fvmoraes/ginger/pkg/config"
)

// PT-BR: Load lê a configuração da aplicação.
// EN: Load reads the application configuration.
func Load() (*gingercfg.Config, error) {
	return gingercfg.Load("configs/app.yaml")
}
`

const healthHandlerTmpl = generatedGoFileHeader + `package handlers

import (
	"context"

	"github.com/fvmoraes/ginger/pkg/health"
)

type staticChecker struct {
	name string
}

func (c staticChecker) Name() string { return c.name }

func (c staticChecker) Check(context.Context) error { return nil }

// RegisterHealthChecks registers starter health checks for the generated service.
func RegisterHealthChecks(h *health.Handler) {
	h.Register(staticChecker{name: "app"})
}
`

const appYamlTmpl = `app:
  name: {{.Name}}
  env: development
  version: 0.1.0

http:
  host: 0.0.0.0
  port: 8080
  shutdown_timeout: 30

log:
  level: info
  format: json
`

const envExampleTmpl = `APP_NAME={{.Name}}
APP_ENV=development
HTTP_PORT=8080
LOG_LEVEL=info
LOG_FORMAT=json
DATABASE_DRIVER=postgres
DATABASE_DSN=postgres://user:pass@localhost:5432/{{.Name}}?sslmode=disable
`

const dockerfileTmpl = `FROM golang:{{.GoVersion}}-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o bin/{{.Name}} ./{{.CmdDir}}

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/bin/{{.Name}} .
COPY --from=builder /app/configs ./configs
EXPOSE 8080
ENTRYPOINT ["./{{.Name}}"]
`

const dockerComposeTmpl = `version: "3.9"

services:
  {{.Name}}:
    build:
      context: ../..
      dockerfile: devops/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_ENV: development
      HTTP_PORT: 8080
      DATABASE_DSN: postgres://user:pass@postgres:5432/{{.Name}}?sslmode=disable
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: {{.Name}}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata:
`

const prometheusConfigTmpl = `global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "{{.Name}}"
    static_configs:
      - targets: ["{{.Name}}:8080"]
`

const k8sDeploymentTmpl = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    app: {{.Name}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Name}}
  template:
    metadata:
      labels:
        app: {{.Name}}
    spec:
      containers:
        - name: {{.Name}}
          image: {{.Name}}:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{.Name}}-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
spec:
  selector:
    app: {{.Name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
`

const helmChartTmpl = `apiVersion: v2
name: {{.Name}}
description: Helm chart for {{.Name}}
type: application
version: 0.1.0
appVersion: "0.1.0"
`

const helmValuesTmpl = `replicaCount: 2

image:
  repository: {{.Name}}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  APP_ENV: production
  HTTP_PORT: "8080"
`

const helmDeploymentTmpl = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ "{{" }} .Release.Name {{ "}}" }}
spec:
  replicas: {{ "{{" }} .Values.replicaCount {{ "}}" }}
  selector:
    matchLabels:
      app: {{ "{{" }} .Release.Name {{ "}}" }}
  template:
    metadata:
      labels:
        app: {{ "{{" }} .Release.Name {{ "}}" }}
    spec:
      containers:
        - name: {{ "{{" }} .Release.Name {{ "}}" }}
          image: "{{ "{{" }} .Values.image.repository {{ "}}" }}:{{ "{{" }} .Values.image.tag {{ "}}" }}"
          ports:
            - containerPort: {{ "{{" }} .Values.service.targetPort {{ "}}" }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ "{{" }} .Values.service.targetPort {{ "}}" }}
          resources:
            {{- "{{" }} toYaml .Values.resources | nindent 12 {{ "}}" }}
`

const makefileTmpl = `BIN=bin/{{.Name}}

.PHONY: run build test lint tidy{{if or (eq .Type "service") (eq .Type "worker")}} docker{{end}}{{if eq .Type "service"}} up down{{end}}

run:
	go run ./{{.CmdDir}}

build:
	go build -o $(BIN) ./{{.CmdDir}}

test:
	go test ./...

lint:
	golangci-lint run ./...

tidy:
	go mod tidy
{{if or (eq .Type "service") (eq .Type "worker")}}
docker:
	docker build -f devops/docker/Dockerfile -t {{.Name}}:latest .
{{end}}{{if eq .Type "service"}}
up:
	docker compose -f devops/docker/docker-compose.yml up -d

down:
	docker compose -f devops/docker/docker-compose.yml down
{{end}}
`

const pipelineTmpl = `name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go test ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go build -o bin/{{.Name}} ./{{.CmdDir}}
`

const gitignoreTmpl = `bin/
*.env
.env
*.log
.DS_Store
.vscode/
.idea/
`

const readmeTmpl = `# {{.Name}}

A Ginger-powered Go application (type: {{.Type}}).

Generated with Go {{.GoVersion}} or the minimum supported version when the local toolchain is older or unavailable.

## Getting started

` + "```" + `bash
go mod tidy
make run
` + "```" + `
{{if or (eq .Type "service") (eq .Type "worker")}}
## DevOps

` + "```" + `bash
make docker  # builds using devops/docker/Dockerfile
{{if eq .Type "service"}}
make up      # starts app + postgres + redis + prometheus + grafana
make down    # stops everything
{{end}}
` + "```" + `
{{end}}
## Project structure

` + "```" + `
{{.CmdDir}}/       # Application entrypoint{{if or (eq .Type "service") (eq .Type "worker")}}
configs/          # YAML config files{{end}}{{if eq .Type "service"}}

internal/
  api/
    handlers/     # Starts with health.go
  config/         # Config loader{{end}}{{if eq .Type "worker"}}

internal/
  worker/         # Worker loop{{end}}{{if or (eq .Type "service") (eq .Type "worker")}}

devops/
  docker/         # Dockerfile{{if eq .Type "service"}}, compose and Prometheus config{{end}}
{{if eq .Type "service"}}  kubernetes/     # K8s manifests
  helm/           # Helm chart
{{end}}  pipelines/      # CI/CD sample
{{end}}
` + "```" + `

Ginger keeps new projects minimal.
Directories like ` + "`platform/`" + `, ` + "`tests/`" + `, extra ` + "`internal/api/...`" + ` layers, and additional ` + "`devops/`" + ` assets appear only when you generate or add them.
`

// ─── Shared ─────────────────────────────────────────────────────────────────

const editorconfigTmpl = `root = true

[*]
indent_style = tab
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.go]
indent_style = tab
indent_size = 4

[*.{yaml,yml,json,md}]
indent_style = space
indent_size = 2
`

// ─── CLI app template (--cli) ────────────────────────────────────────────────

const cliAppMainTmpl = generatedGoFileHeader + `package main

import (
	"os"

	"{{.Module}}/internal/commands"
)

func main() {
	if err := commands.Execute(); err != nil {
		os.Exit(1)
	}
}
`

const cliRootCommandTmpl = generatedGoFileHeader + `package commands

import (
	"fmt"

	"github.com/spf13/cobra"
)

var (
	verbose bool
	output  string
	cfgFile string
)

var rootCmd = &cobra.Command{
	Use:   "{{.Name}}",
	Short: "{{.Name}} — a Ginger-powered CLI",
	Long: ` + "`" + `{{.Name}} is a CLI application built with Ginger.

Use --help on any subcommand for details.` + "`" + `,
	Example: ` + "`" + `  {{.Name}} version
  {{.Name}} completion zsh > _{{.Name}}` + "`" + `,
	SilenceUsage: true,
}

// Execute runs the root command.
func Execute() error {
	return rootCmd.Execute()
}

func init() {
	rootCmd.PersistentFlags().BoolVarP(&verbose, "verbose", "v", false, "enable verbose output")
	rootCmd.PersistentFlags().StringVarP(&output, "output", "o", "text", "output format: text, json, table")
	rootCmd.PersistentFlags().StringVarP(&cfgFile, "config", "c", "", "config file (default: $HOME/.{{.Name}}.yaml)")
	rootCmd.PersistentFlags().Bool("no-color", false, "disable color output")
	rootCmd.AddCommand(newCompletionCmd())
}

func newCompletionCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "completion [bash|zsh|fish]",
		Short: "Generate shell completion scripts",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			switch args[0] {
			case "bash":
				return rootCmd.GenBashCompletion(cmd.OutOrStdout())
			case "zsh":
				return rootCmd.GenZshCompletion(cmd.OutOrStdout())
			case "fish":
				return rootCmd.GenFishCompletion(cmd.OutOrStdout(), true)
			default:
				return fmt.Errorf("unsupported shell %q", args[0])
			}
		},
	}
}
`

const cliVersionCommandTmpl = generatedGoFileHeader + `package commands

import (
	"fmt"

	"github.com/spf13/cobra"
)

// These are set via -ldflags at build time.
var (
	version = "dev"
	commit  = "none"
	date    = "unknown"
)

var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Print version information",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Printf("{{.Name}} %s (commit: %s, built: %s)\n", version, commit, date)
	},
}

func init() {
	rootCmd.AddCommand(versionCmd)
}
`

const cliPortsTmpl = generatedGoFileHeader + `package ports

import "io"

// FileReader reads a named file and returns its contents.
type FileReader interface {
	ReadFile(name string) ([]byte, error)
}

// ConfigLoader loads application configuration from a named source.
type ConfigLoader interface {
	Load(source string) (map[string]any, error)
}

// Writer is a generic output writer.
type Writer interface {
	io.Writer
}
`

const cliFilesystemAdapterTmpl = generatedGoFileHeader + `package adapters

import "os"

// Filesystem implements ports.FileReader using the local filesystem.
type Filesystem struct{}

// NewFilesystem returns a new Filesystem adapter.
func NewFilesystem() *Filesystem { return &Filesystem{} }

// ReadFile reads the file at name and returns its contents.
func (f *Filesystem) ReadFile(name string) ([]byte, error) {
	return os.ReadFile(name)
}
`

const cliConfigTmpl = generatedGoFileHeader + `package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// Config holds application configuration.
type Config struct {
	App struct {
		Name string ` + "`yaml:\"name\"`" + `
		Env  string ` + "`yaml:\"env\"`" + `
	} ` + "`yaml:\"app\"`" + `
}

// Load reads configuration from the given YAML file path.
// Falls back to sensible defaults if the file is not found.
func Load(path string) (*Config, error) {
	cfg := &Config{}
	cfg.App.Name = "{{.Name}}"
	cfg.App.Env = "development"

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return cfg, nil
		}
		return nil, fmt.Errorf("config: read %s: %w", path, err)
	}

	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("config: parse %s: %w", path, err)
	}

	return cfg, nil
}
`

const cliOutputFormatterTmpl = generatedGoFileHeader + `package output

import (
	"encoding/json"
	"fmt"
	"io"
	"text/tabwriter"
)

// Format is the output format.
type Format string

const (
	FormatText  Format = "text"
	FormatJSON  Format = "json"
	FormatTable Format = "table"
)

// Formatter writes structured output in the chosen format.
type Formatter struct {
	w      io.Writer
	format Format
}

// New returns a Formatter writing to w in the given format.
func New(w io.Writer, format Format) *Formatter {
	return &Formatter{w: w, format: format}
}

// Print writes v in the configured format.
func (f *Formatter) Print(v any) error {
	switch f.format {
	case FormatJSON:
		enc := json.NewEncoder(f.w)
		enc.SetIndent("", "  ")
		return enc.Encode(v)
	case FormatTable:
		tw := tabwriter.NewWriter(f.w, 0, 0, 2, ' ', 0)
		fmt.Fprintf(tw, "%v\n", v)
		return tw.Flush()
	default: // text
		fmt.Fprintf(f.w, "%v\n", v)
		return nil
	}
}
`

const goreleaserTmpl = `# .goreleaser.yaml — generated by Ginger
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: {{.Name}}
    main: ./{{.CmdDir}}
    binary: {{.Name}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X {{.Module}}/internal/commands.version={{ "{{" }}.Version{{ "}}" }}
      - -X {{.Module}}/internal/commands.commit={{ "{{" }}.Commit{{ "}}" }}
      - -X {{.Module}}/internal/commands.date={{ "{{" }}.Date{{ "}}" }}

archives:
  - format: tar.gz
    name_template: "{{.Name}}_{{ "{{" }}.Version{{ "}}" }}_{{ "{{" }}.Os{{ "}}" }}_{{ "{{" }}.Arch{{ "}}" }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
`

// ─── Worker templates ────────────────────────────────────────────────────────

const workerHandlerTmpl = generatedGoFileHeader + `package worker

import "context"

// Handler processes a single message.
// Return a non-nil error to signal that the message should be retried.
type Handler interface {
	Handle(ctx context.Context, msg []byte) error
}

// DefaultHandler is a no-op handler used as a placeholder.
type DefaultHandler struct{}

// Handle logs the message and returns nil (acknowledge).
func (h *DefaultHandler) Handle(ctx context.Context, msg []byte) error {
	// PT-BR: Substitua esta implementação pela lógica de negócio real.
	// EN: Replace this implementation with real business logic.
	_ = msg
	return nil
}
`

const workerPortsTmpl = generatedGoFileHeader + `package ports

import "context"

// MessageConsumer receives messages from a queue or topic.
type MessageConsumer interface {
	Consume(ctx context.Context) (<-chan []byte, error)
	Ack(ctx context.Context, msg []byte) error
	Nack(ctx context.Context, msg []byte) error
}

// MessagePublisher sends messages to a queue or topic.
type MessagePublisher interface {
	Publish(ctx context.Context, topic string, msg []byte) error
}

// JobStore persists job state.
type JobStore interface {
	Save(ctx context.Context, id string, payload []byte) error
	Load(ctx context.Context, id string) ([]byte, error)
}
`

const workerMemoryConsumerTmpl = generatedGoFileHeader + `package adapters

import (
	"context"
	"sync"
)

// MemoryConsumer is an in-memory MessageConsumer for development and testing.
type MemoryConsumer struct {
	mu   sync.Mutex
	msgs [][]byte
	ch   chan []byte
}

// NewMemoryConsumer returns a new MemoryConsumer.
func NewMemoryConsumer() *MemoryConsumer {
	return &MemoryConsumer{ch: make(chan []byte, 64)}
}

// Push enqueues a message (for testing / local use).
func (m *MemoryConsumer) Push(msg []byte) {
	m.ch <- msg
}

// Consume returns the internal channel. Calling this multiple times returns the same channel.
func (m *MemoryConsumer) Consume(_ context.Context) (<-chan []byte, error) {
	return m.ch, nil
}

// Ack is a no-op for the in-memory adapter.
func (m *MemoryConsumer) Ack(_ context.Context, _ []byte) error { return nil }

// Nack is a no-op for the in-memory adapter.
func (m *MemoryConsumer) Nack(_ context.Context, _ []byte) error { return nil }
`

const workerProcessorTmpl = generatedGoFileHeader + `package services

import (
	"context"
	"fmt"
)

// Processor holds business logic for processing messages.
type Processor struct{}

// NewProcessor returns a new Processor.
func NewProcessor() *Processor { return &Processor{} }

// ProcessMessage processes a single raw message payload.
// Replace this stub with real domain logic.
func (p *Processor) ProcessMessage(ctx context.Context, msg []byte) error {
	if len(msg) == 0 {
		return fmt.Errorf("processor: empty message")
	}
	// PT-BR: Adicione a lógica de processamento aqui.
	// EN: Add processing logic here.
	return nil
}
`

const workerIntegrationTestTmpl = `package integration_test

import (
	"context"
	"testing"
	"time"

	"{{.Module}}/internal/adapters"
	"{{.Module}}/internal/worker"
)

func TestWorkerProcessesMessage(t *testing.T) {
	consumer := adapters.NewMemoryConsumer()
	w := worker.New(consumer, &worker.DefaultHandler{})

	ctx, cancel := context.WithTimeout(context.Background(), 300*time.Millisecond)
	defer cancel()

	consumer.Push([]byte("hello"))

	errCh := make(chan error, 1)
	go func() { errCh <- w.Run(ctx) }()

	select {
	case err := <-errCh:
		if err != nil {
			t.Fatalf("worker returned error: %v", err)
		}
	case <-time.After(3 * time.Second):
		t.Fatal("worker did not stop within timeout")
	}
}
`

const workerDockerComposeTmpl = `version: "3.9"
# PT-BR: Este compose contém apenas o serviço worker.
# EN: This compose contains only the worker service.
# Use 'ginger add rabbitmq' (or kafka/nats/redis/postgres) to add infrastructure services.

services:
  {{.Name}}:
    build:
      context: ../..
      dockerfile: devops/docker/Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: development
`

// ─── Service templates ───────────────────────────────────────────────────────

const serviceRouterTmpl = generatedGoFileHeader + `package api

import (
	"net/http"

	"{{.Module}}/internal/api/middlewares"
	"github.com/fvmoraes/ginger/pkg/response"
	"github.com/fvmoraes/ginger/pkg/router"
)

var generatedRouteRegistrars []func(*router.Router)

// Register wires starter routes onto Ginger's shared router.
func Register(r *router.Router) {
	// PT-BR: Agrupe as rotas da API sob /api/v1.
	// EN: Group API routes under /api/v1.
	v1 := r.Group("/api/v1", middlewares.RequestID)
	registerCoreRoutes(v1)
	registerGeneratedRoutes(v1)
}

func registerCoreRoutes(v1 *router.Router) {
	v1.GET("/ping", func(w http.ResponseWriter, _ *http.Request) {
		response.OK(w, map[string]any{"status": "ok"})
	})
}

func registerGeneratedRoutes(v1 *router.Router) {
	for _, register := range generatedRouteRegistrars {
		register(v1)
	}
}
`

const serviceRequestIDMiddlewareTmpl = generatedGoFileHeader + `package middlewares

import (
	"net/http"

	"github.com/google/uuid"
)

const headerRequestID = "X-Request-ID"

// RequestID injects a unique request ID into every response header.
// If the incoming request already carries X-Request-ID, it is propagated as-is.
func RequestID(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		id := r.Header.Get(headerRequestID)
		if id == "" {
			id = uuid.NewString()
		}
		w.Header().Set(headerRequestID, id)
		next.ServeHTTP(w, r)
	})
}
`

const servicePortsTmpl = generatedGoFileHeader + `package ports

import "context"

// Store is a generic key-value store interface.
// Replace or extend with domain-specific repository interfaces as the project grows.
type Store interface {
	Get(ctx context.Context, key string) ([]byte, error)
	Set(ctx context.Context, key string, value []byte) error
	Delete(ctx context.Context, key string) error
}
`

const serviceMemoryStoreTmpl = generatedGoFileHeader + `package adapters

import (
	"context"
	"fmt"
	"sync"
)

// MemoryStore is an in-memory Store implementation for development and testing.
type MemoryStore struct {
	mu   sync.RWMutex
	data map[string][]byte
}

// NewMemoryStore returns a new MemoryStore.
func NewMemoryStore() *MemoryStore {
	return &MemoryStore{data: make(map[string][]byte)}
}

// Get retrieves the value for key.
func (s *MemoryStore) Get(_ context.Context, key string) ([]byte, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	v, ok := s.data[key]
	if !ok {
		return nil, fmt.Errorf("store: key not found: %s", key)
	}
	return v, nil
}

// Set stores value under key.
func (s *MemoryStore) Set(_ context.Context, key string, value []byte) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.data[key] = value
	return nil
}

// Delete removes key from the store.
func (s *MemoryStore) Delete(_ context.Context, key string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.data, key)
	return nil
}
`

const serviceHealthTestTmpl = `package integration_test

import (
	"net/http"
	"testing"

	"{{.Module}}/internal/api"
	"{{.Module}}/internal/api/handlers"
	"{{.Module}}/internal/config"
	gingerapp "github.com/fvmoraes/ginger/pkg/app"
	"github.com/fvmoraes/ginger/pkg/testhelper"
)

func TestHealthEndpoint(t *testing.T) {
	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("config.Load returned error: %v", err)
	}

	app := gingerapp.New(cfg)
	handlers.RegisterHealthChecks(app.Health)
	api.Register(app.Router)

	rec := testhelper.NewRequest(t, app.Router, http.MethodGet, "/health").Do()
	testhelper.AssertStatus(t, rec, http.StatusOK)
}
`
