package generator

const generatedGoFileHeader = `// PT-BR: Arquivo gerado pelo Ginger. Revise e adapte este código ao seu domínio.
// EN: File generated by Ginger. Review and adapt this code to your domain.

`

const handlerTmpl = generatedGoFileHeader + `package handlers

import (
	"net/http"

	"{{.Module}}/internal/models"
	"{{.Module}}/internal/services"
	"github.com/fvmoraes/ginger/pkg/response"
	"github.com/fvmoraes/ginger/pkg/router"
)

type {{.NameTitle}}Handler struct {
	svc services.{{.NameTitle}}Service
}

func New{{.NameTitle}}Handler(svc services.{{.NameTitle}}Service) *{{.NameTitle}}Handler {
	return &{{.NameTitle}}Handler{svc: svc}
}

func (h *{{.NameTitle}}Handler) Register(r *router.Router) {
	g := r.Group("/{{.NamePlural}}")
	g.GET("/", h.list)
	g.GET("/{id}", h.get)
	g.POST("/", h.create)
	g.PUT("/{id}", h.update)
	g.DELETE("/{id}", h.delete)
}

func (h *{{.NameTitle}}Handler) list(w http.ResponseWriter, r *http.Request) {
	items, err := h.svc.List(r.Context())
	if err != nil {
		router.Error(w, err)
		return
	}
	response.OK(w, items)
}

func (h *{{.NameTitle}}Handler) get(w http.ResponseWriter, r *http.Request) {
	item, err := h.svc.Get(r.Context(), r.PathValue("id"))
	if err != nil {
		router.Error(w, err)
		return
	}
	response.OK(w, item)
}

func (h *{{.NameTitle}}Handler) create(w http.ResponseWriter, r *http.Request) {
	var input models.Create{{.NameTitle}}Input
	if err := router.Decode(r, &input); err != nil {
		router.Error(w, err)
		return
	}

	item, err := h.svc.Create(r.Context(), input)
	if err != nil {
		router.Error(w, err)
		return
	}
	response.Created(w, item)
}

func (h *{{.NameTitle}}Handler) update(w http.ResponseWriter, r *http.Request) {
	var input models.Update{{.NameTitle}}Input
	if err := router.Decode(r, &input); err != nil {
		router.Error(w, err)
		return
	}

	item, err := h.svc.Update(r.Context(), r.PathValue("id"), input)
	if err != nil {
		router.Error(w, err)
		return
	}
	response.OK(w, item)
}

func (h *{{.NameTitle}}Handler) delete(w http.ResponseWriter, r *http.Request) {
	if err := h.svc.Delete(r.Context(), r.PathValue("id")); err != nil {
		router.Error(w, err)
		return
	}
	response.NoContent(w)
}
`

const serviceTmpl = generatedGoFileHeader + `package services

import (
	"context"
	"time"

	"{{.Module}}/internal/models"
	"{{.Module}}/internal/ports"
)

type {{.NameTitle}}Service interface {
	List(ctx context.Context) ([]models.{{.NameTitle}}, error)
	Get(ctx context.Context, id string) (models.{{.NameTitle}}, error)
	Create(ctx context.Context, input models.Create{{.NameTitle}}Input) (models.{{.NameTitle}}, error)
	Update(ctx context.Context, id string, input models.Update{{.NameTitle}}Input) (models.{{.NameTitle}}, error)
	Delete(ctx context.Context, id string) error
}

type {{.Name}}Service struct {
	repo ports.{{.NameTitle}}Repository
}

func New{{.NameTitle}}Service(repo ports.{{.NameTitle}}Repository) {{.NameTitle}}Service {
	return &{{.Name}}Service{repo: repo}
}

func (s *{{.Name}}Service) List(ctx context.Context) ([]models.{{.NameTitle}}, error) {
	return s.repo.List(ctx)
}

func (s *{{.Name}}Service) Get(ctx context.Context, id string) (models.{{.NameTitle}}, error) {
	return s.repo.Get(ctx, id)
}

func (s *{{.Name}}Service) Create(ctx context.Context, input models.Create{{.NameTitle}}Input) (models.{{.NameTitle}}, error) {
	item := models.{{.NameTitle}}{
		ID:        input.Name,
		Name:      input.Name,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	return s.repo.Create(ctx, item)
}

func (s *{{.Name}}Service) Update(ctx context.Context, id string, input models.Update{{.NameTitle}}Input) (models.{{.NameTitle}}, error) {
	current, err := s.repo.Get(ctx, id)
	if err != nil {
		return models.{{.NameTitle}}{}, err
	}
	if input.Name != "" {
		current.Name = input.Name
	}
	current.UpdatedAt = time.Now()
	return s.repo.Update(ctx, id, current)
}

func (s *{{.Name}}Service) Delete(ctx context.Context, id string) error {
	return s.repo.Delete(ctx, id)
}
`

const repositoryTmpl = generatedGoFileHeader + `package ports

import (
	"context"

	"{{.Module}}/internal/models"
)

type {{.NameTitle}}Repository interface {
	List(ctx context.Context) ([]models.{{.NameTitle}}, error)
	Get(ctx context.Context, id string) (models.{{.NameTitle}}, error)
	Create(ctx context.Context, item models.{{.NameTitle}}) (models.{{.NameTitle}}, error)
	Update(ctx context.Context, id string, item models.{{.NameTitle}}) (models.{{.NameTitle}}, error)
	Delete(ctx context.Context, id string) error
}
`

const adapterTmpl = generatedGoFileHeader + `package adapters

import (
	"context"
	"fmt"
	"sync"

	"{{.Module}}/internal/models"
)

type {{.NameTitle}}MemoryRepository struct {
	mu    sync.RWMutex
	items map[string]models.{{.NameTitle}}
}

func New{{.NameTitle}}MemoryRepository() *{{.NameTitle}}MemoryRepository {
	return &{{.NameTitle}}MemoryRepository{items: make(map[string]models.{{.NameTitle}})}
}

func (r *{{.NameTitle}}MemoryRepository) List(context.Context) ([]models.{{.NameTitle}}, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	items := make([]models.{{.NameTitle}}, 0, len(r.items))
	for _, item := range r.items {
		items = append(items, item)
	}
	return items, nil
}

func (r *{{.NameTitle}}MemoryRepository) Get(_ context.Context, id string) (models.{{.NameTitle}}, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	item, ok := r.items[id]
	if !ok {
		return models.{{.NameTitle}}{}, fmt.Errorf("{{.Slug}} not found: %s", id)
	}
	return item, nil
}

func (r *{{.NameTitle}}MemoryRepository) Create(_ context.Context, item models.{{.NameTitle}}) (models.{{.NameTitle}}, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.items[item.ID] = item
	return item, nil
}

func (r *{{.NameTitle}}MemoryRepository) Update(_ context.Context, id string, item models.{{.NameTitle}}) (models.{{.NameTitle}}, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	item.ID = id
	r.items[id] = item
	return item, nil
}

func (r *{{.NameTitle}}MemoryRepository) Delete(_ context.Context, id string) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	delete(r.items, id)
	return nil
}
`

const modelTmpl = generatedGoFileHeader + `package models

import "time"

type {{.NameTitle}} struct {
	ID        string    ` + "`json:\"id\"`" + `
	Name      string    ` + "`json:\"name\"`" + `
	CreatedAt time.Time ` + "`json:\"created_at\"`" + `
	UpdatedAt time.Time ` + "`json:\"updated_at\"`" + `
}

type Create{{.NameTitle}}Input struct {
	Name string ` + "`json:\"name\"`" + `
}

type Update{{.NameTitle}}Input struct {
	Name string ` + "`json:\"name\"`" + `
}
`

const handlerTestTmpl = generatedGoFileHeader + `package handlers

import (
	"net/http"
	"testing"

	"{{.Module}}/internal/adapters"
	"{{.Module}}/internal/services"
	"github.com/fvmoraes/ginger/pkg/router"
	"github.com/fvmoraes/ginger/pkg/testhelper"
)

func Test{{.NameTitle}}Handler_Register(t *testing.T) {
	repo := adapters.New{{.NameTitle}}MemoryRepository()
	svc := services.New{{.NameTitle}}Service(repo)
	h := New{{.NameTitle}}Handler(svc)
	r := router.New()
	h.Register(r)

	tests := []struct {
		name       string
		method     string
		path       string
		body       any
		wantStatus int
	}{
		{name: "list", method: http.MethodGet, path: "/{{.NamePlural}}/", wantStatus: http.StatusOK},
		{name: "create", method: http.MethodPost, path: "/{{.NamePlural}}/", body: map[string]any{"name": "{{.Slug}}"}, wantStatus: http.StatusCreated},
		{name: "get", method: http.MethodGet, path: "/{{.NamePlural}}/{{.Slug}}", wantStatus: http.StatusOK},
		{name: "update", method: http.MethodPut, path: "/{{.NamePlural}}/{{.Slug}}", body: map[string]any{"name": "{{.Slug}} updated"}, wantStatus: http.StatusOK},
		{name: "delete", method: http.MethodDelete, path: "/{{.NamePlural}}/{{.Slug}}", wantStatus: http.StatusNoContent},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := testhelper.NewRequest(t, r, tt.method, tt.path)
			if tt.body != nil {
				req = req.WithBody(tt.body)
			}
			rec := req.Do()
			testhelper.AssertStatus(t, rec, tt.wantStatus)
		})
	}
}
`

const serviceTestTmpl = generatedGoFileHeader + `package services

import (
	"context"
	"testing"

	"{{.Module}}/internal/adapters"
	"{{.Module}}/internal/models"
)

func Test{{.NameTitle}}Service_CRUD(t *testing.T) {
	svc := New{{.NameTitle}}Service(adapters.New{{.NameTitle}}MemoryRepository())
	ctx := context.Background()

	created, err := svc.Create(ctx, models.Create{{.NameTitle}}Input{Name: "{{.Slug}}"})
	if err != nil {
		t.Fatalf("Create returned error: %v", err)
	}
	if created.Name != "{{.Slug}}" {
		t.Fatalf("expected created name %q, got %q", "{{.Slug}}", created.Name)
	}

	items, err := svc.List(ctx)
	if err != nil {
		t.Fatalf("List returned error: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("expected 1 item, got %d", len(items))
	}
}
`

const repositoryTestTmpl = generatedGoFileHeader + `package adapters

import (
	"context"
	"testing"
	"time"

	"{{.Module}}/internal/models"
)

func Test{{.NameTitle}}MemoryRepository_CRUD(t *testing.T) {
	repo := New{{.NameTitle}}MemoryRepository()
	ctx := context.Background()

	item := models.{{.NameTitle}}{
		ID:        "{{.Slug}}",
		Name:      "{{.Slug}}",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	if _, err := repo.Create(ctx, item); err != nil {
		t.Fatalf("Create returned error: %v", err)
	}

	got, err := repo.Get(ctx, "{{.Slug}}")
	if err != nil {
		t.Fatalf("Get returned error: %v", err)
	}
	if got.Name != item.Name {
		t.Fatalf("expected %q, got %q", item.Name, got.Name)
	}
}
`

const integrationTestTmpl = generatedGoFileHeader + `package integration_test

import (
	"net/http"
	"testing"

	"{{.Module}}/internal/adapters"
	"{{.Module}}/internal/api/handlers"
	"{{.Module}}/internal/services"
	"github.com/fvmoraes/ginger/pkg/router"
	"github.com/fvmoraes/ginger/pkg/testhelper"
)

func Test{{.NameTitle}}CRUDFlow(t *testing.T) {
	repo := adapters.New{{.NameTitle}}MemoryRepository()
	svc := services.New{{.NameTitle}}Service(repo)
	h := handlers.New{{.NameTitle}}Handler(svc)
	r := router.New()
	v1 := r.Group("/api/v1")
	h.Register(v1)

	create := testhelper.NewRequest(t, r, http.MethodPost, "/api/v1/{{.NamePlural}}/").
		WithBody(map[string]any{"name": "{{.Slug}}"}).
		Do()
	testhelper.AssertStatus(t, create, http.StatusCreated)

	list := testhelper.NewRequest(t, r, http.MethodGet, "/api/v1/{{.NamePlural}}/").Do()
	testhelper.AssertStatus(t, list, http.StatusOK)
}
`

const appTestTmpl = generatedGoFileHeader + `package integration_test

import (
	"net/http"
	"testing"

	"{{.Module}}/internal/api"
	"{{.Module}}/internal/api/handlers"
	"{{.Module}}/internal/config"
	gingerapp "github.com/fvmoraes/ginger/pkg/app"
	"github.com/fvmoraes/ginger/pkg/testhelper"
)

func TestApp_Smoke(t *testing.T) {
	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("config.Load returned error: %v", err)
	}

	app := gingerapp.New(cfg)
	handlers.RegisterHealthChecks(app.Health)
	api.Register(app.Router)

	rec := testhelper.NewRequest(t, app.Router, http.MethodGet, "/health").Do()
	testhelper.AssertStatus(t, rec, http.StatusOK)
}
`

const cliServicePortTmpl = generatedGoFileHeader + `package ports

import "context"

type {{.NameTitle}}Runner interface {
	Run(ctx context.Context, args []string) error
}
`

const cliServiceTmpl = generatedGoFileHeader + `package services

import (
	"context"
	"fmt"
)

type {{.NameTitle}} struct{}

func New{{.NameTitle}}() *{{.NameTitle}} { return &{{.NameTitle}}{} }

func (s *{{.NameTitle}}) Run(ctx context.Context, args []string) error {
	_ = ctx
	fmt.Printf("{{.Slug}} service executed with %d args\n", len(args))
	return nil
}
`

const cliServiceTestTmpl = generatedGoFileHeader + `package services

import (
	"context"
	"testing"
)

func Test{{.NameTitle}}Run(t *testing.T) {
	if err := New{{.NameTitle}}().Run(context.Background(), []string{"example"}); err != nil {
		t.Fatalf("Run returned error: %v", err)
	}
}
`

const workerServicePortTmpl = generatedGoFileHeader + `package ports

import "context"

type {{.NameTitle}}Processor interface {
	Process(ctx context.Context, msg []byte) error
}
`

const workerServiceTmpl = generatedGoFileHeader + `package services

import (
	"context"
	"fmt"
)

type {{.NameTitle}} struct{}

func New{{.NameTitle}}() *{{.NameTitle}} { return &{{.NameTitle}}{} }

func (s *{{.NameTitle}}) Process(ctx context.Context, msg []byte) error {
	_ = ctx
	if len(msg) == 0 {
		return fmt.Errorf("{{.Slug}}: empty message")
	}
	return nil
}
`

const workerServiceTestTmpl = generatedGoFileHeader + `package services

import (
	"context"
	"testing"
)

func Test{{.NameTitle}}Process(t *testing.T) {
	if err := New{{.NameTitle}}().Process(context.Background(), []byte("hello")); err != nil {
		t.Fatalf("Process returned error: %v", err)
	}
}
`

const openAPITmpl = `{
  "openapi": "3.0.3",
  "info": {
    "title": "Ginger API",
    "version": "1.0.0",
    "description": "Starter OpenAPI document generated by Ginger"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Local development"
    }
  ],
  "paths": {
    "/health": {
      "get": {
        "summary": "Health check",
        "responses": {
          "200": {
            "description": "Healthy"
          }
        }
      }
    }{{if .Name}},
    "/{{.NamePlural}}/": {
      "get": {
        "summary": "List {{.NamePlural}}",
        "tags": ["{{.NameTitle}}"],
        "responses": {
          "200": {
            "description": "List of {{.NamePlural}}"
          }
        }
      },
      "post": {
        "summary": "Create {{.NameTitle}}",
        "tags": ["{{.NameTitle}}"],
        "responses": {
          "201": {
            "description": "{{.NameTitle}} created"
          }
        }
      }
    }{{end}}
  }
}
`
