package generator

const generatedGoFileHeader = `// PT-BR: Arquivo gerado pelo Ginger. Revise e adapte este código ao seu domínio.
// EN: File generated by Ginger. Review and adapt this code to your domain.

`

const handlerTmpl = generatedGoFileHeader + `package handlers

import (
	"net/http"

	"github.com/fvmoraes/ginger/pkg/response"
	"github.com/fvmoraes/ginger/pkg/router"
)

// PT-BR: {{.NameTitle}}Handler lida com requisições HTTP de {{.NamePlural}}.
// EN: {{.NameTitle}}Handler handles HTTP requests for {{.NamePlural}}.
type {{.NameTitle}}Handler struct {
	// PT-BR: svc representa o serviço de {{.NameTitle}}.
	// EN: svc represents the {{.NameTitle}} service.
}

// PT-BR: New{{.NameTitle}}Handler cria um novo {{.NameTitle}}Handler.
// EN: New{{.NameTitle}}Handler creates a new {{.NameTitle}}Handler.
func New{{.NameTitle}}Handler( /* svc {{.NameTitle}}Service */ ) *{{.NameTitle}}Handler {
	return &{{.NameTitle}}Handler{}
}

// PT-BR: Register monta as rotas de {{.NameTitle}} no grupo informado.
// EN: Register mounts the {{.NameTitle}} routes on the given router group.
func (h *{{.NameTitle}}Handler) Register(r *router.Router) {
	g := r.Group("/{{.NamePlural}}")
	g.GET("/", h.list)
	g.GET("/{id}", h.get)
	g.POST("/", h.create)
	g.PUT("/{id}", h.update)
	g.DELETE("/{id}", h.delete)
}

func (h *{{.NameTitle}}Handler) list(w http.ResponseWriter, r *http.Request) {
	response.OK(w, []any{})
}

func (h *{{.NameTitle}}Handler) get(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	response.OK(w, map[string]string{"id": id})
}

func (h *{{.NameTitle}}Handler) create(w http.ResponseWriter, r *http.Request) {
	var body map[string]any
	if err := router.Decode(r, &body); err != nil {
		router.Error(w, err)
		return
	}
	response.Created(w, body)
}

func (h *{{.NameTitle}}Handler) update(w http.ResponseWriter, r *http.Request) {
	var body map[string]any
	if err := router.Decode(r, &body); err != nil {
		router.Error(w, err)
		return
	}
	response.OK(w, body)
}

func (h *{{.NameTitle}}Handler) delete(w http.ResponseWriter, r *http.Request) {
	response.NoContent(w)
}
`

const serviceTmpl = generatedGoFileHeader + `package services

import "context"

// PT-BR: {{.NameTitle}}Service define a logica de negocio de {{.NamePlural}}.
// EN: {{.NameTitle}}Service defines the business logic for {{.NamePlural}}.
type {{.NameTitle}}Service interface {
	List(ctx context.Context) ([]any, error)
	Get(ctx context.Context, id string) (any, error)
	Create(ctx context.Context, input any) (any, error)
	Update(ctx context.Context, id string, input any) (any, error)
	Delete(ctx context.Context, id string) error
}

type {{.Name}}Service struct {
	// PT-BR: repo representa o repositorio de {{.NameTitle}}.
	// EN: repo represents the {{.NameTitle}} repository.
}

// PT-BR: New{{.NameTitle}}Service cria um novo {{.Name}}Service.
// EN: New{{.NameTitle}}Service creates a new {{.Name}}Service.
func New{{.NameTitle}}Service( /* repo {{.NameTitle}}Repository */ ) {{.NameTitle}}Service {
	return &{{.Name}}Service{}
}

func (s *{{.Name}}Service) List(ctx context.Context) ([]any, error) {
	return []any{}, nil
}

func (s *{{.Name}}Service) Get(ctx context.Context, id string) (any, error) {
	return map[string]string{"id": id}, nil
}

func (s *{{.Name}}Service) Create(ctx context.Context, input any) (any, error) {
	return input, nil
}

func (s *{{.Name}}Service) Update(ctx context.Context, id string, input any) (any, error) {
	return input, nil
}

func (s *{{.Name}}Service) Delete(ctx context.Context, id string) error {
	return nil
}
`

const repositoryTmpl = generatedGoFileHeader + `package repositories

import (
	"context"
	"database/sql"
)

// PT-BR: {{.NameTitle}}Repository define o acesso a dados de {{.NamePlural}}.
// EN: {{.NameTitle}}Repository defines data access for {{.NamePlural}}.
type {{.NameTitle}}Repository interface {
	FindAll(ctx context.Context) ([]any, error)
	FindByID(ctx context.Context, id string) (any, error)
	Save(ctx context.Context, entity any) (any, error)
	Update(ctx context.Context, id string, entity any) (any, error)
	Delete(ctx context.Context, id string) error
}

type {{.Name}}Repository struct {
	db *sql.DB
}

// PT-BR: New{{.NameTitle}}Repository cria um novo {{.Name}}Repository.
// EN: New{{.NameTitle}}Repository creates a new {{.Name}}Repository.
func New{{.NameTitle}}Repository(db *sql.DB) {{.NameTitle}}Repository {
	return &{{.Name}}Repository{db: db}
}

func (r *{{.Name}}Repository) FindAll(ctx context.Context) ([]any, error) {
	return []any{}, nil
}

func (r *{{.Name}}Repository) FindByID(ctx context.Context, id string) (any, error) {
	return map[string]string{"id": id}, nil
}

func (r *{{.Name}}Repository) Save(ctx context.Context, entity any) (any, error) {
	return entity, nil
}

func (r *{{.Name}}Repository) Update(ctx context.Context, id string, entity any) (any, error) {
	return entity, nil
}

func (r *{{.Name}}Repository) Delete(ctx context.Context, id string) error {
	return nil
}
`

const modelTmpl = generatedGoFileHeader + `package models

import "time"

// PT-BR: {{.NameTitle}} representa o modelo de dominio de {{.NamePlural}}.
// EN: {{.NameTitle}} is the domain model for {{.NamePlural}}.
type {{.NameTitle}} struct {
	ID        string    ` + "`json:\"id\"`" + `
	CreatedAt time.Time ` + "`json:\"created_at\"`" + `
	UpdatedAt time.Time ` + "`json:\"updated_at\"`" + `
}

// PT-BR: Create{{.NameTitle}}Input representa o payload para criar um(a) {{.Name}}.
// EN: Create{{.NameTitle}}Input is the payload for creating a {{.Name}}.
type Create{{.NameTitle}}Input struct {
	// PT-BR: TODO: adicione os campos necessarios.
	// EN: TODO: add the required fields.
}

// PT-BR: Update{{.NameTitle}}Input representa o payload para atualizar um(a) {{.Name}}.
// EN: Update{{.NameTitle}}Input is the payload for updating a {{.Name}}.
type Update{{.NameTitle}}Input struct {
	// PT-BR: TODO: adicione os campos necessarios.
	// EN: TODO: add the required fields.
}
`

const handlerTestTmpl = generatedGoFileHeader + `package handlers

import (
	"net/http"
	"testing"

	"github.com/fvmoraes/ginger/pkg/router"
	"github.com/fvmoraes/ginger/pkg/testhelper"
)

func Test{{.NameTitle}}Handler_Register(t *testing.T) {
	h := New{{.NameTitle}}Handler()
	r := router.New()
	h.Register(r)

	tests := []struct {
		name       string
		method     string
		path       string
		body       any
		wantStatus int
	}{
		{
			name:       "list {{.NamePlural}}",
			method:     http.MethodGet,
			path:       "/{{.NamePlural}}/",
			wantStatus: http.StatusOK,
		},
		{
			name:   "create {{.Name}}",
			method: http.MethodPost,
			path:   "/{{.NamePlural}}/",
			body:       map[string]any{"name": "{{.Name}}"},
			wantStatus: http.StatusCreated,
		},
		{
			name:       "get {{.Name}} by id",
			method:     http.MethodGet,
			path:       "/{{.NamePlural}}/123",
			wantStatus: http.StatusOK,
		},
		{
			name:   "update {{.Name}}",
			method: http.MethodPut,
			path:   "/{{.NamePlural}}/123",
			body:   map[string]any{"name": "{{.Name}} updated"},
			wantStatus: http.StatusOK,
		},
		{
			name:       "delete {{.Name}}",
			method:     http.MethodDelete,
			path:       "/{{.NamePlural}}/123",
			wantStatus: http.StatusNoContent,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := testhelper.NewRequest(t, r, tt.method, tt.path)
			if tt.body != nil {
				req = req.WithBody(tt.body)
			}
			rec := req.Do()
			testhelper.AssertStatus(t, rec, tt.wantStatus)
		})
	}
}
`

const serviceTestTmpl = generatedGoFileHeader + `package services

import (
	"context"
	"reflect"
	"testing"
)

func Test{{.NameTitle}}Service_CRUD(t *testing.T) {
	svc := New{{.NameTitle}}Service()
	ctx := context.Background()

	list, err := svc.List(ctx)
	if err != nil {
		t.Fatalf("List returned error: %v", err)
	}
	if len(list) != 0 {
		t.Fatalf("expected empty list, got %d items", len(list))
	}

	got, err := svc.Get(ctx, "123")
	if err != nil {
		t.Fatalf("Get returned error: %v", err)
	}
	entity, ok := got.(map[string]string)
	if !ok {
		t.Fatalf("expected map[string]string, got %T", got)
	}
	if entity["id"] != "123" {
		t.Fatalf("expected id 123, got %q", entity["id"])
	}

	input := map[string]any{"name": "{{.Name}}"}

	created, err := svc.Create(ctx, input)
	if err != nil {
		t.Fatalf("Create returned error: %v", err)
	}
	if !reflect.DeepEqual(created, input) {
		t.Fatalf("expected Create to return input, got %#v", created)
	}

	updated, err := svc.Update(ctx, "123", input)
	if err != nil {
		t.Fatalf("Update returned error: %v", err)
	}
	if !reflect.DeepEqual(updated, input) {
		t.Fatalf("expected Update to return input, got %#v", updated)
	}

	if err := svc.Delete(ctx, "123"); err != nil {
		t.Fatalf("Delete returned error: %v", err)
	}
}
`

const repositoryTestTmpl = generatedGoFileHeader + `package repositories

import (
	"context"
	"reflect"
	"testing"
)

func Test{{.NameTitle}}Repository_CRUD(t *testing.T) {
	repo := New{{.NameTitle}}Repository(nil)
	ctx := context.Background()

	list, err := repo.FindAll(ctx)
	if err != nil {
		t.Fatalf("FindAll returned error: %v", err)
	}
	if len(list) != 0 {
		t.Fatalf("expected empty list, got %d items", len(list))
	}

	got, err := repo.FindByID(ctx, "123")
	if err != nil {
		t.Fatalf("FindByID returned error: %v", err)
	}
	entity, ok := got.(map[string]string)
	if !ok {
		t.Fatalf("expected map[string]string, got %T", got)
	}
	if entity["id"] != "123" {
		t.Fatalf("expected id 123, got %q", entity["id"])
	}

	input := map[string]any{"name": "{{.Name}}"}

	saved, err := repo.Save(ctx, input)
	if err != nil {
		t.Fatalf("Save returned error: %v", err)
	}
	if !reflect.DeepEqual(saved, input) {
		t.Fatalf("expected Save to return input, got %#v", saved)
	}

	updated, err := repo.Update(ctx, "123", input)
	if err != nil {
		t.Fatalf("Update returned error: %v", err)
	}
	if !reflect.DeepEqual(updated, input) {
		t.Fatalf("expected Update to return input, got %#v", updated)
	}

	if err := repo.Delete(ctx, "123"); err != nil {
		t.Fatalf("Delete returned error: %v", err)
	}
}
`

const appTestTmpl = generatedGoFileHeader + `package integration_test

import (
	"net/http"
	"testing"

	"{{.Module}}/internal/api/handlers"
	"{{.Module}}/internal/config"
	gingerapp "github.com/fvmoraes/ginger/pkg/app"
	"github.com/fvmoraes/ginger/pkg/testhelper"
)

func TestApp_Smoke(t *testing.T) {
	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("config.Load returned error: %v", err)
	}

	app := gingerapp.New(cfg)
	handlers.Register(app.Router)

	tests := []struct {
		name       string
		method     string
		path       string
		wantStatus int
	}{
		{
			name:       "health endpoint",
			method:     http.MethodGet,
			path:       "/health",
			wantStatus: http.StatusOK,
		},
		{
			name:       "root endpoint",
			method:     http.MethodGet,
			path:       "/",
			wantStatus: http.StatusOK,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rec := testhelper.NewRequest(t, app.Router, tt.method, tt.path).Do()
			testhelper.AssertStatus(t, rec, tt.wantStatus)
		})
	}
}
`

const openAPITmpl = `{
  "openapi": "3.0.3",
  "info": {
    "title": "Ginger API",
    "version": "1.0.0",
    "description": "Starter OpenAPI document generated by Ginger"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Local development"
    }
  ],
  "paths": {
    "/health": {
      "get": {
        "summary": "Health check",
        "responses": {
          "200": {
            "description": "Healthy"
          }
        }
      }
    }{{if .Name}},
    "/{{.NamePlural}}/": {
      "get": {
        "summary": "List {{.NamePlural}}",
        "tags": ["{{.NameTitle}}"],
        "responses": {
          "200": {
            "description": "List of {{.NamePlural}}"
          }
        }
      },
      "post": {
        "summary": "Create {{.Name}}",
        "tags": ["{{.NameTitle}}"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Create{{.NameTitle}}Input"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "{{.NameTitle}} created"
          }
        }
      }
    },
    "/{{.NamePlural}}/{id}": {
      "get": {
        "summary": "Get {{.Name}} by ID",
        "tags": ["{{.NameTitle}}"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "{{.NameTitle}} details"
          }
        }
      },
      "put": {
        "summary": "Update {{.Name}}",
        "tags": ["{{.NameTitle}}"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Update{{.NameTitle}}Input"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "{{.NameTitle}} updated"
          }
        }
      },
      "delete": {
        "summary": "Delete {{.Name}}",
        "tags": ["{{.NameTitle}}"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "{{.NameTitle}} deleted"
          }
        }
      }
    }{{end}}
  }{{if .Name}},
  "components": {
    "schemas": {
      "{{.NameTitle}}": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "name": { "type": "string", "example": "{{.Name}}" }
        }
      },
      "Create{{.NameTitle}}Input": {
        "type": "object",
        "properties": {
          "name": { "type": "string", "example": "{{.Name}}" }
        },
        "required": ["name"]
      },
      "Update{{.NameTitle}}Input": {
        "type": "object",
        "properties": {
          "name": { "type": "string", "example": "{{.Name}} updated" }
        }
      }
    }
  }{{end}}
}
`
